# Generated by Django 4.1.5 on 2023-01-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
