# Generated by Django 4.1.5 on 2023-01-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_sub_category_created_at_sub_category_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
