# Generated by Django 4.1.5 on 2023-01-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_sub_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_name',
            field=models.CharField(max_length=50),
        ),
    ]
