# Generated by Django 4.1.5 on 2023-01-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_sub_category_sub_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
