# Generated by Django 4.1.5 on 2023-02-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
