# Generated by Django 4.1.5 on 2023-01-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
