# Generated by Django 4.1.5 on 2023-01-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_value',
        ),
    ]
