# Generated by Django 4.1.5 on 2023-01-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_variation_variation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
