# Generated by Django 4.1.5 on 2023-02-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
