# Generated by Django 4.1.5 on 2023-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=200),
        ),
    ]
