# Generated by Django 4.1.5 on 2023-02-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_products_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
