# Generated by Django 4.1.5 on 2023-01-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=3, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
