# Generated by Django 4.1.5 on 2023-01-08 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mixins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mixins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
