# Generated by Django 4.1.5 on 2023-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_remove_mixins_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixins',
            name='mobile',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
