# Generated by Django 4.1.5 on 2023-01-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_mixins_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mixins',
            old_name='mobile',
            new_name='phone',
        ),
    ]
