# Generated by Django 4.1.5 on 2023-01-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_remove_mixins_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixins',
            name='phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
