# Generated by Django 4.1.5 on 2023-01-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_mixins_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mixins',
        ),
    ]
