# Generated by Django 4.1.5 on 2023-01-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
