# Generated by Django 4.1.5 on 2023-01-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_products_stock_variation_stock'),
        ('order', '0003_alter_orderproduct_color_alter_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.variation'),
        ),
    ]
