# Generated by Django 4.1.5 on 2023-02-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.FloatField(default=0),
        ),
    ]
